apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: movie-grabber

resources:
  - ../../base

images:
  - name: movie-grabber-api
    newName: ghcr.io/s3nthilg0pal/movie-grabber
    newTag: main

replicas:
  - name: movie-grabber-api
    count: 1
